apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodeployment
  name: mongodeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodeployment
    spec:
      containers:
      - image: mongo
        name: mongo
        resources: {}
status: {}
